
import React from 'react';
import { ModelOption, ChatConfig, AppTheme, UserProfile, Role, ChatSession } from './types';

// Use 127.0.0.1 to avoid DNS resolution issues on some Termux/Android setups
// CHANGED TO HTTPS
export const LOCAL_SERVER_URL = 'https://127.0.0.1:3001/data';

export const INITIAL_CONFIG: ChatConfig = {
  provider: 'google',
  googleAuthMode: 'key',
  apiUrl: '',
  apiKey: '',
  model: '',
  systemInstruction: '你是一个乐于助人且简洁的AI助手。',
  temperature: 1.0,
  topP: 0.95,
  topK: 64,
  enableSearch: false,
  historyLimit: 20, 
  thinkingBudget: 0, 
  enableStream: true, 
  enableStickers: false,
  enableTransfer: false, // Default off
  dialogueMode: 'normal', // Default normal
  visualMemoryLimit: 3,
};

export const MOCK_CHATS: ChatSession[] = [
  {
    id: '1',
    name: 'AI 助手',
    avatar: 'https://picsum.photos/seed/assist/200/200',
    messages: [
      {
        id: 'msg-0',
        role: Role.MODEL,
        content: '你好！我是你的AI助手。请点击右上角的 "..." 设置 API 和模型开始聊天。',
        timestamp: Date.now(),
      },
    ],
    config: { ...INITIAL_CONFIG }, 
  },
];

export const DEFAULT_THEME: AppTheme = {
  userBubbleColor: '#95ec69', // WeChat Green
  botBubbleColor: '#ffffff',
  backgroundColor: '#f5f5f5',
  actionTextColor: '#888888', // Default gray
};

export const DEFAULT_PROFILE: UserProfile = {
  name: '我',
  avatar: 'https://picsum.photos/seed/user/200/200',
  wechatId: 'wxid_ai_user',
  stickers: [],
};

export const AVATAR_USER = DEFAULT_PROFILE.avatar;

export const SERVER_SCRIPT_CONTENT = [
  "const https = require('https');",
  "const fs = require('fs');",
  "const path = require('path');",
  "const { execSync } = require('child_process');",
  "",
  "const PORT = 3001;",
  "const HOST = '0.0.0.0'; // Allow access from local network",
  "const DATA_FILE = path.join(__dirname, 'chat_data.json');",
  "const KEY_FILE = path.join(__dirname, 'key.pem');",
  "const CERT_FILE = path.join(__dirname, 'cert.pem');",
  "",
  "// ANSI Colors for Termux",
  "const CLR = {",
  "    Reset: \"\\x1b[0m\",",
  "    Red: \"\\x1b[31m\",",
  "    Green: \"\\x1b[32m\",",
  "    Yellow: \"\\x1b[33m\",",
  "    Blue: \"\\x1b[36m\",",
  "    Magenta: \"\\x1b[35m\",",
  "    Cyan: \"\\x1b[36m\",",
  "    Dim: \"\\x1b[2m\",",
  "    Bold: \"\\x1b[1m\"",
  "};",
  "",
  "const getTimestamp = () => {",
  "    return new Date().toLocaleTimeString('en-US', { hour12: false });",
  "};",
  "",
  "const log = (type, msg, details = '') => {",
  "    const time = getTimestamp();",
  "    let color = CLR.Reset;",
  "    let icon = '•';",
  "    ",
  "    if (type === 'GET') { color = CLR.Cyan; icon = '⬇'; }",
  "    if (type === 'POST') { color = CLR.Green; icon = '⬆'; }",
  "    if (type === 'ERR') { color = CLR.Red; icon = '✖'; }",
  "    if (type === 'INFO') { color = CLR.Yellow; icon = 'ℹ'; }",
  "    if (type === 'OPTIONS') { color = CLR.Dim; icon = '◌'; }",
  "",
  "    console.log(",
  "        CLR.Dim + '[' + time + ']' + CLR.Reset + ' ' + ",
  "        color + icon + ' ' + type.padEnd(7) + CLR.Reset + ' ' + ",
  "        msg + ' ' + (details ? CLR.Dim + details + CLR.Reset : '')",
  "    );",
  "};",
  "",
  "// --- 0. SSL Certificate Generation ---",
  "if (!fs.existsSync(KEY_FILE) || !fs.existsSync(CERT_FILE)) {",
  "    console.log(CLR.Yellow + 'Creating SSL Certificates...' + CLR.Reset);",
  "    try {",
  "        // Use openssl to generate self-signed cert (Default in Termux via openssl-tool)",
  "        execSync('openssl req -nodes -new -x509 -keyout key.pem -out cert.pem -days 365 -subj \"/CN=localhost\"');",
  "        console.log(CLR.Green + 'Certificates generated successfully.' + CLR.Reset);",
  "    } catch (e) {",
  "        console.error(CLR.Red + 'Failed to generate SSL certificates!' + CLR.Reset);",
  "        console.error('Please install openssl in Termux by running:');",
  "        console.error(CLR.Bold + 'pkg install openssl-tool' + CLR.Reset);",
  "        process.exit(1);",
  "    }",
  "}",
  "",
  "const options = {",
  "    key: fs.readFileSync(KEY_FILE),",
  "    cert: fs.readFileSync(CERT_FILE)",
  "};",
  "",
  "const server = https.createServer(options, (req, res) => {",
  "  // --- 1. Robust CORS ---",
  "  const origin = req.headers.origin || '*';",
  "  res.setHeader('Access-Control-Allow-Origin', origin);",
  "  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');",
  "  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization, X-Requested-With');",
  "  res.setHeader('Access-Control-Allow-Credentials', 'true');",
  "  res.setHeader('Access-Control-Allow-Private-Network', 'true');",
  "",
  "  const clientIp = req.socket.remoteAddress;",
  "",
  "  // --- 2. Handle Preflight ---",
  "  if (req.method === 'OPTIONS') {",
  "    log('OPTIONS', 'Preflight Check', 'from ' + clientIp);",
  "    res.writeHead(204);",
  "    res.end();",
  "    return;",
  "  }",
  "",
  "  // --- 3. Heartbeat (Silent) ---",
  "  if (req.url === '/ping') {",
  "      res.writeHead(200);",
  "      res.end('pong');",
  "      return;",
  "  }",
  "",
  "  // --- 4. GET /data ---",
  "  // NOTE: Supports query params e.g. /data?t=...",
  "  if (req.method === 'GET' && req.url.startsWith('/data')) {",
  "    fs.readFile(DATA_FILE, 'utf8', (err, data) => {",
  "      if (err) {",
  "        if (err.code === 'ENOENT') {",
  "            log('GET', 'Data Init (New File)', 'from ' + clientIp);",
  "            res.writeHead(200, { 'Content-Type': 'application/json' });",
  "            res.end(JSON.stringify([]));",
  "        } else {",
  "            log('ERR', 'Read Failed', err.message);",
  "            res.writeHead(500, { 'Content-Type': 'application/json' });",
  "            res.end(JSON.stringify({ error: 'Failed to read data' }));",
  "        }",
  "      } else {",
  "        const sizeKB = (Buffer.byteLength(data) / 1024).toFixed(2);",
  "        log('GET', 'Data Read', sizeKB + ' KB sent to ' + clientIp);",
  "        res.writeHead(200, { 'Content-Type': 'application/json' });",
  "        res.end(data);",
  "      }",
  "    });",
  "  }",
  "  // --- 5. POST /data ---",
  "  else if (req.method === 'POST' && req.url.startsWith('/data')) {",
  "    const chunks = [];",
  "    req.on('data', chunk => chunks.push(chunk));",
  "    req.on('error', (err) => {",
  "        log('ERR', 'Stream Error', err.message);",
  "        res.writeHead(500);",
  "        res.end();",
  "    });",
  "    req.on('end', () => {",
  "      const body = Buffer.concat(chunks).toString();",
  "      try {",
  "          JSON.parse(body); // Validate JSON",
  "          const sizeKB = (Buffer.byteLength(body) / 1024).toFixed(2);",
  "          ",
  "          fs.writeFile(DATA_FILE, body, (err) => {",
  "            if (err) {",
  "              log('ERR', 'Write Failed', err.message);",
  "              res.writeHead(500, { 'Content-Type': 'application/json' });",
  "              res.end(JSON.stringify({ error: 'Failed to save data' }));",
  "            } else {",
  "              log('POST', 'Data Saved', sizeKB + ' KB received from ' + clientIp);",
  "              res.writeHead(200, { 'Content-Type': 'application/json' });",
  "              res.end(JSON.stringify({ success: true }));",
  "            }",
  "          });",
  "      } catch (e) {",
  "          log('ERR', 'Invalid JSON', 'from ' + clientIp);",
  "          res.writeHead(400, { 'Content-Type': 'application/json' });",
  "          res.end(JSON.stringify({ error: 'Invalid JSON' }));",
  "      }",
  "    });",
  "  } else {",
  "    if (req.url === '/') {",
  "        res.writeHead(200);",
  "        res.end('WeChat AI Local Server Running (HTTPS)');",
  "    } else {",
  "        res.writeHead(404);",
  "        res.end('Not Found');",
  "    }",
  "  }",
  "});",
  "",
  "server.listen(PORT, HOST, () => {",
  "  console.clear();",
  "  console.log(CLR.Green);",
  "  console.log('=================================================');",
  "  console.log(' WECHAT AI - LOCAL SERVER RUNNING (v1.3 HTTPS)');",
  "  console.log('=================================================');",
  "  console.log(' Status:   ' + CLR.Bold + 'ONLINE (HTTPS)' + CLR.Reset);",
  "  console.log(' Address:  https://' + HOST + ':' + PORT);",
  "  console.log(' DataFile: ' + DATA_FILE);",
  "  console.log(' Logs:     Real-time requests below...');",
  "  console.log('=================================================' + CLR.Reset + '\\n');",
  "});"
].join('\n');
